apiVersion: delivery.ocm.software/v1alpha1
kind: Unpacker
metadata:
  name: podify
  namespace: ocm-system
spec:
  interval: 10m0s
  prune: true
  componentVersionRef:
    name: podify
    namespace: ocm-system
  resourceSelector:
    skipRoot: true
    followReferences: true
    matchSelector:
    - field: "type"
      values:
      - kustomize.ocm.fluxcd.io
  pipelineTemplateRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
    path: ./templates/podify.yaml
  values:
    frontend:
      manifests:
        message: "Welcome to podify"
        color: "red"
